<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-YourLocalShopMVC-1694ea22-45f6-4899-88c5-64394e3d33eb</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Areas\Identity\Data\**" />
    <Content Remove="Areas\Identity\Data\**" />
    <EmbeddedResource Remove="Areas\Identity\Data\**" />
    <None Remove="Areas\Identity\Data\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Data\AccountsDbContext.cs.bup" />
    <None Remove="Data\ShopInventoryContext.cs.bup" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="8.0.21" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.21" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.21" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.21" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.21" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.7" />
  </ItemGroup>

</Project>
